{% set name = "dbt-artifacts-parser" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 072f614c8082c4423c03af538e911c0181518e82123fa53240f9afa4391edc5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7.0
    - pydantic >=2.0,<3.0

test:
  imports:
    - dbt_artifacts_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yu-iskw/dbt-artifacts-parser
  summary: A dbt artifacts parser in python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
