{% set name = "dbt-artifacts-parser" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-artifacts-parser-{{ version }}.tar.gz
  sha256: 543448b84989ac65ea53b2cf0ee37e71572eecd31e7dcb0f1ecb544cdf60c73c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7.0
    - pydantic >=1.6
    - datamodel-code-generator >=0.12.0

test:
  source_files:
    - tests
  imports:
    - dbt_artifacts_parser
  commands:
  # Skipping pip check test because prance version number cannot be parsed correctly
  #   - pip check
  # Tests are implemented in a strange way so for now we have to skip for now
  #  - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/yu-iskw/dbt-artifacts-parser
  summary: A dbt artifacts parser in python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
