{% set name = "dbt-artifacts-parser" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt-artifacts-parser-{{ version }}.tar.gz
  sha256: 174c6b5f44e41b1bbd0055d7a1439bc07a2be445aca26948382f3ab427b8228c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7.0
    - pydantic >=1.6
    - datamodel-code-generator >=0.12.0

test:
  imports:
    - dbt_artifacts_parser
  # Skipping pip check test because prance version number cannot be parsed correctly
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/yu-iskw/dbt-artifacts-parser
  summary: A dbt artifacts parser in python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
