{% set name = "dbt-artifacts-parser" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8cb8d4621dcbe6482dbecb79567a5bf40aa9cb15dbcd24eedff09d0218254afd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7.0
    - pydantic >=1.6,<2.0
    - datamodel-code-generator >=0.12.0

test:
  imports:
    - dbt_artifacts_parser
  commands:
    # Skipping pip check test because prance version number cannot be parsed correctly
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/yu-iskw/dbt-artifacts-parser
  summary: A dbt artifacts parser in python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
