schema_version: 1

context:
  name: dbt-artifacts-parser
  version: "0.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 48f71c984913af888dffc8317d2b83f195370cb02fc439961198357533a6b859

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.0,<3.0

tests:
  - python:
      imports:
        - dbt_artifacts_parser
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A dbt artifacts parser in python
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/yu-iskw/dbt-artifacts-parser

extra:
  recipe-maintainers:
    - thewchan
